### ISSUE TITLE
Compatibility issues with some Windows machines

### ISSUE THREAD

**Issue by willgraf** [vanvalenlab/kiosk-imageJ-plugin#15]
<img width="494" alt="image" src="https://user-images.githubusercontent.com/7930703/91874425-10575b80-ec2f-11ea-9f70-d78ad0d7a7d5.png">

**Comment by willgraf** [comment]
Another error popped up using FIJI and Win10:

```
(Fiji Is Just) ImageJ 2.1.0/1.53c; Java 1.8.0_172 [64-bit]; Windows 10 10.0; 250MB of 24463MB (1%)
java.lang.NullPointerException
	at org.vanvalenlab.ImageJobManager.run(ImageJobManager.java:22)
	at ij.IJ.runUserPlugIn(IJ.java:235)
	at ij.IJ.runPlugIn(IJ.java:198)
	at ij.Executer.runCommand(Executer.java:150)
	at ij.Executer.run(Executer.java:68)
	at java.lang.Thread.run(Thread.java:748)
```
