### ISSUE TITLE
FileNotFoundException if input file is too large.

### ISSUE THREAD

**Issue by willgraf** [vanvalenlab/kiosk-imageJ-plugin#19]
The following error was encountered when trying to process a multiplex image of size (2000, 2600). While this job _should_ fail, it should fail with the consumer's image size error, not the error found below:

```
java.io.FileNotFoundException: nullStack.tif (The system cannot find the file specified)
	at java.io.FileInputStream.open0(Native Method)
	at java.io.FileInputStream.open(FileInputStream.java:195)
	at java.io.FileInputStream.<init>(FileInputStream.java:138)
	at okio.Okio__JvmOkioKt.source(JvmOkio.kt:178)
	at okio.Okio.source(Unknown Source)
	at okhttp3.RequestBody$Companion$asRequestBody$1.writeTo(RequestBody.kt:167)
	at okhttp3.MultipartBody.writeOrCountBytes(MultipartBody.kt:157)
	at okhttp3.MultipartBody.writeTo(MultipartBody.kt:93)
	at okhttp3.internal.http.CallServerInterceptor.intercept(CallServerInterceptor.kt:59)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:100)
	at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.kt:34)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:100)
	at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.kt:96)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:100)
	at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.kt:83)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:100)
	at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.kt:76)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:100)
	at okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp(RealCall.kt:197)
	at okhttp3.internal.connection.RealCall.execute(RealCall.kt:148)
	at org.vanvalenlab.KioskHttpClient.sendHttpRequest(KioskHttpClient.java:35)
	at org.vanvalenlab.KioskHttpClient.uploadFile(KioskHttpClient.java:87)
	at org.vanvalenlab.KioskJob.create(KioskJob.java:89)
	at org.vanvalenlab.KioskJobManager.runJob(KioskJobManager.java:112)
	at org.vanvalenlab.ImageJobManager.run(ImageJobManager.java:35)
	at ij.IJ.runUserPlugIn(IJ.java:235)
	at ij.IJ.runPlugIn(IJ.java:198)
	at ij.Executer.runCommand(Executer.java:150)
	at ij.Executer.run(Executer.java:68)
	at java.lang.Thread.run(Thread.java:748)
```

The original image was then cropped and uploaded/processed successfully.

**Comment by willgraf** [comment]
I'm looking into this error now and cannot reproduce it exactly. Instead I get the following error: `java.net.SocketException: Broken pipe (Write failed)`.
