### ISSUE TITLE
Error when submitting an image that was created in ImageJ

### ISSUE THREAD

**Issue by ngreenwald** [vanvalenlab/kiosk-imageJ-plugin#20]
I'm getting the following error when I try and submit an image that was created in ImageJ. Specifically, if I separately load a nuclear channel, membrane channel, and them combine them together in ImageJ, it fails. Saving that combined image to disk, and then loading it, does not produce an error. 

```
(Fiji Is Just) ImageJ 2.1.0/1.53c; Java 1.8.0_172 [64-bit]; Mac OS X 10.14.6; 279MB of 20677MB (1%)
 
java.io.FileNotFoundException: /Users/noahgreenwald/Downloads (Is a directory)
	at java.io.FileInputStream.open0(Native Method)
	at java.io.FileInputStream.open(FileInputStream.java:195)
	at java.io.FileInputStream.<init>(FileInputStream.java:138)
	at okio.Okio__JvmOkioKt.source(JvmOkio.kt:178)
	at okio.Okio.source(Unknown Source)
	at okhttp3.RequestBody$Companion$asRequestBody$1.writeTo(RequestBody.kt:167)
	at okhttp3.MultipartBody.writeOrCountBytes(MultipartBody.kt:157)
	at okhttp3.MultipartBody.writeTo(MultipartBody.kt:93)
	at okhttp3.internal.http.CallServerInterceptor.intercept(CallServerInterceptor.kt:59)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:100)
	at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.kt:34)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:100)
	at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.kt:96)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:100)
	at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.kt:83)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:100)
	at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.kt:76)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:100)
	at okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp(RealCall.kt:197)
	at okhttp3.internal.connection.RealCall.execute(RealCall.kt:148)
	at org.vanvalenlab.KioskHttpClient.sendHttpRequest(KioskHttpClient.java:35)
	at org.vanvalenlab.KioskHttpClient.uploadFile(KioskHttpClient.java:87)
	at org.vanvalenlab.KioskJob.create(KioskJob.java:90)
	at org.vanvalenlab.KioskJobManager.runJob(KioskJobManager.java:112)
	at org.vanvalenlab.ImageJobManager.run(ImageJobManager.java:35)
	at ij.IJ.runUserPlugIn(IJ.java:235)
	at ij.IJ.runPlugIn(IJ.java:198)
	at ij.Executer.runCommand(Executer.java:150)
	at ij.Executer.run(Executer.java:68)
	at java.lang.Thread.run(Thread.java:748)

```

**Comment by willgraf** [comment]
Sounds like we should be able to save the combined file as a temporary file and upload it to resolve the issue.
